// Generated by CoffeeScript 1.11.1
'use strict';
var webpack, webpackConfig;

webpack = require('webpack');

webpackConfig = {
  context: __dirname,
  output: {
    publicPath: 'http://localhost:8080/scripts/',
    path: __dirname + '/dist/scripts',
    filename: 'bundle.js'
  },
  devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
  },
  resolve: {
    alias: {
      'jquery.ui.widget': 'jquery.ui.widget/jquery.ui.widget.js'
    },
    modules: ['node_modules', 'assets/src'],
    extensions: ['*', '.js', '.jsx', '.cjsx', '.coffee']
  },
  cache: true,
  devtool: false,
  entry: ['webpack-dev-server/client?http://0.0.0.0:8080', './index.jsx'],
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development')
    }), new webpack.HotModuleReplacementPlugin(), new webpack.LoaderOptionsPlugin({
      debug: true
    })
  ],
  stats: {
    colors: true,
    reasons: true
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      }, {
        test: /\.sass$/,
        use: ['style-loader', 'css-loader', 'sass-loader?indentedSyntax']
      }, {
        test: /\.gif/,
        use: ['url-loader?limit=100000&minetype=image/gif']
      }, {
        test: /\.jpg/,
        use: ['url-loader?limit=100000&minetype=image/jpg']
      }, {
        test: /\.png/,
        use: ['url-loader?limit=100000&minetype=image/png']
      }, {
        test: /\.jsx$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015', 'react']
          }
        }
      }, {
        test: /\.coffee$/,
        use: ['coffee-loader']
      }, {
        test: /\.(woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: ['url-loader?limit=10000&mimetype=application/font-woff']
      }, {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: ['file-loader']
      }
    ]
  }
};

module.exports = webpackConfig;
